# General configuration for the application
name = "youwished-app"
version = "0.0.2"
api_version = 1
environment = "development" # "development" or "production"

# Database configuration
[database]
    localhost = "http://localhost"

    [database.couchdb]
    host = "127.0.0.1"
    port = "5984"
    databases = ["wishes"]