# General configuration for the application
[app]
name = "youwished-app"
version = "0.0.2"
environment = "development" # "development" or "production"

[api]
version = 1
root =  "/api"
host = "localhost"
port =  3000

# Database configuration
[database]
    localhost = "http://localhost"

    [database.couchdb]
    host = "127.0.0.1"
    port = "5984"
    databases = ["wishes"]